In [1]:
import numpy as np
import pandas as pd
from textblob import TextBlob
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import nltk
import re
import math
import string
from wordcloud import WordCloud, STOPWORDS
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.stem import SnowballStemmer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
import datetime
import gensim
from nltk.stem import WordNetLemmatizer



tensor([[0.8294, 0.4467, 0.6588],
        [0.9598, 0.9173, 0.2108]], device='cuda:0')


In [2]:
mystopwords = ['ltc', 'product', 'ought', 'gorgeous', 'time', 'btc', 'btc ', 'bitcoin', 'bitcoin ', 'revoluciónde', 'free', 'coincheck', 'dash', 'usd', 'post', 'cryptoworld', 'ico', 'powell', 'eth', 'doge', 'xrp', 'xpc', 'price ', 'crypto', 'buy', 'market', 'amp', 'sell', 'bch', 'cryptocurrency', 'money', 'like', 'news', 'volume', 'new', 'earn', 'exchange', 'current', 'mine', 'cash', 'coin', 'blockchain', 'go', 'join', 'good', 'jpy', 'people', 'link', 'start', 'ethereum', 'world', 'change', 'think', 'xlm', 'twitter', 'look', 'value', 'project', 'know', 'binance', 'use', 'come', 'long', 'eos', 'short', 'pay', 'worth', 'need', 'want', 'block', 'day', 'today', 'invest', 'get', 'daily', 'best', 'say', 'profit', 'thank', 'wallet', 'gold', 'neo', 'great', 'info', 'que', 'bank', 'trx', 'account', 'check', 'read', 'bnb', 'noticias', 'update', 'xmr', 'follow', 'usdt', 'forex', 'ada', 'days', 'support', 'currency', 'fee', 'work', 'hour', 'right', 'signal', 'utc', 'average', 'investment', 'way', 'analysis', 'sign', 'help', 'hold', 'high', 'tweet', 'break', 'com', 'eur', 'future', 'cann', 'emc', 'btg', 'extremely', 'hard', 'truth', 'rule', 'busy', 'jerome', 'hace', 'caer', 'ask', 'bid', 'alert', 'currently', 'round', 'participants', 'hereistitle', 'setup', 'automatic', 'bitcome', 'automatically', 'businesses', 'minutes', 'sleep', 'idol', 'sit', 'generate', 'bitco', 'aud', 'trxprice', 'discount', 'feereceive', 'coinbasewaves', 'grs', 'xvg', 'mco', 'omg', 'btcd', 'devastadoras', 'para', 'planeta', 'menos', 'décadas', 'xem', 'lsk', 'mona', 'number', 'miner', 'unknown', 'transactions', 'size', 'bytes', 'total', 'supply', 'issue', '草コイン', '仮想通貨', 'cap', 'billion', 'base', 'bpi', 'cloud', 'gominer', 'instant', 'witdraw', 'litecoin', 'iota', 'channel', 'ocn', 'iost', 'ncash', 'storm', 'cdt', 'ven', 'gvt', 'lisk', 'appc', 'mod', 'nebl', 'enj', 'precio', 'fuente', 'hora', 'gmt', 'satoshi', 'waste', 'register', 'payouts', 'verify', 'valor', 'aumentou', 'caiu', 'actual', 'del', 'mxn', 'compra', 'vende', 'ripple', 'desde', 'aqu', 'unique', 'modern', 'win', 'strategies', 'develop', 'directly', 'traders', 'company', 'low', 'ビットコイン', 'bitflyer', 'spot', 'bitmex', 'finex', 'frr', 'smart', 'trader', 'bot', 'andtrailing', 'stop', 'loss', 'pairsauto', 'renew', 'ordersprofit', 'notifications', 'order', 'liquidation', 'perpetualsold', 'jul', 'btcこれによって現在が', '波にしてもc', 'app', 'store', 'catch', 'chance', 'dappt', 'listingvia', 'mercadobitcoin', 'のbtc', 'note第', 'fibonacci', 'fib', 'btcac', 'btcというのもここは前回高値', 'btc逆三尊から開始した上昇', '付近で', 'finex過去の高値は', 'これは日足の雲ですが', 'btcにおいて', '最初にタッチした', '月から', 'さらに', '課題は', 'bybit', 'jun', 'clear', 'task', 'bonus', 'pool', 'participant', 'referal', '週足ベースでの大きな下落後のw', 'report', 'miss', 'close', 'registrations', 'zcl', 'zec', 'snt', 'nxt', 'powr', 'vtc', 'vox', 'dgb', 'coval', 'strat', 'xrb', 'nav', 'weakly', 'trend', 'momentum', 'suggest', 'neutral', 'visit', 'spd', 'yobit', 'hitbtc', 'livecoin', 'dominance', 'max', 'mini', 'brl', 'perpetualbought', 'site', 'terminal', 'large', 'transaction', 'url', 'return', 'asia', 'texas', 'poker', 'sss', 'neteller', 'special', 'rake', 'date', 'power', 'dolar', 'bss', 'nuevos', 'indicadores', 'euro', 'peso', 'col', 'sole', 'chile', 'ここから', '年のように', 'serbest', 'tarih', 'ayar', 'gram', 'çeyrek', 'yarım', 'tam', 'プレゼント', '売買サイン通知', 'bitstamp', 'bitfinex', 'coinbase', 'chxp', 'marvellous', 'maintenance', 'child', 'trade', 'week', 'real', 'network', 'big', 'chart', 'digital', 'run', 'try', 'hit', 'let', 'platform', 'bull', 'make', 'years', 'send', 'leverage', 'year', 'launch', 'bsv', 'address', 'bullish', 'better', 'move', 'drop', 'token', 'million', 'pump', 'latest', 'alts', 'gain', 'interest', 'live', 'receive', 'take', 'watch', 'happen', 'learn', 'guy', 'libra', 'fiat', 'lose', 'give', 'open', 'facebook', 'share', 'offer', 'level', 'wait', 'create', 'mean', 'end', 'btcusd', 'accept', 'dollar', 'tell', 'love', 'list', 'play', 'global', 'game', 'soon', 'increase', 'rise', 'term', 'point', 'talk', 'believe', 'team', 'stock', 'fund', 'hours', 'lot', 'china', 'target', 'futures', 'build', 'telegram', 'add', 'click', 'tokens', 'price', 'source', 'amaze', 'percent', 'lottery', 'jackpot', 'ready', 'zero', 'tradingwin', 'suffer', 'remotely', 'toggle', 'home', 'revolution', 'huge', 'intial', 'model', 'ñol', 'invitation', 'extra', 'instantly', 'recover', 'airdrop', 'act', 'vtho', 'mention', 'website', 'whale', 'alertsomeone', 'marketcap', 'fix', 'summary', 'volatility', 'rank', 'avg', 'pacific', 'height', 'nice', 'you']

punctuation = '!"$%&\'()*+,-./:;<=>?[\\]^_`{|}~•@'         # define a string of punctuation symbols

# Functions to clean tweets
def remove_links(tweet):
    """Takes a string and removes web links from it"""
    tweet = re.sub(r'http\S+', 'http', tweet)   # remove http links
    tweet = re.sub(r'bit.ly/\S+', 'http', tweet)  # remove bitly links
    tweet = tweet.strip('[link]')   # remove [links]
    tweet = re.sub(r'pic.twitter\S+','http', tweet)
    return tweet

def remove_users(tweet):
    """Takes a string and removes retweet and @user information"""
    tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '@', tweet)  # remove re-tweet
    tweet = re.sub('(@[A-Za-z]+[A-Za-z0-9-_]+)', '@', tweet)  # remove tweeted at
    return tweet

def remove_hashtags(tweet):
    """Takes a string and removes any hash tags"""
    tweet = re.sub('(#[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove hash tags
    return tweet

def remove_av(tweet):
    """Takes a string and removes AUDIO/VIDEO tags or labels"""
    tweet = re.sub('VIDEO:', '', tweet)  # remove 'VIDEO:' from start of tweet
    tweet = re.sub('AUDIO:', '', tweet)  # remove 'AUDIO:' from start of tweet
    return tweet

def tokenize(tweet):
    """Returns tokenized representation of words in lemma form excluding stopwords"""
    result = []
    for token in gensim.utils.simple_preprocess(tweet):
        if token not in gensim.parsing.preprocessing.STOPWORDS and token not in mystopwords \
                and len(token) > 2:  # drops words with less than 3 characters
            result.append(lemmatize(token))
    return result

def lemmatize(token):
    """Returns lemmatization of a token"""
    return WordNetLemmatizer().lemmatize(token, pos='v')

def preprocess_tweet(tweet):
    """Main master function to clean tweets, stripping noisy characters, and tokenizing use lemmatization"""
    tweet = remove_users(tweet)
    tweet = remove_links(tweet)
    tweet = remove_hashtags(tweet)
    tweet = remove_av(tweet)
    tweet = re.sub('[' + punctuation + ']+', ' ', tweet)  # strip punctuation
    tweet = re.sub('\s+', ' ', tweet)  # remove double spacing
    tweet = re.sub("[^a-zb(A-Z0-9]+ ", "", tweet)
    return tweet



tensor([[0.4102, 0.4272, 0.5989],
        [0.0288, 0.1383, 0.2290]], device='cuda:0')


In [1]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
import torch

# Preprocess text (username and link placeholders)


def preprocess(text):
    new_text = []

    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Tasks:
# emoji, emotion, hate, irony, offensive, sentiment
# stance/abortion, stance/atheism, stance/climate, stance/feminist, stance/hillary
device ='cuda:0'
task = 'sentiment'
MODEL = f"./twitter-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(MODEL)

# download label mapping
labels = []
mapping_link = f"https://raw.githubusercontent.com/cardiffnlp/tweeteval/main/datasets/{task}/mapping.txt"
with urllib.request.urlopen(mapping_link) as f:
    html = f.read().decode('utf-8').split("\n")
    csvreader = csv.reader(html, delimiter='\t')
labels = [row[1] for row in csvreader if len(row) > 1]

# PT

model = AutoModelForSequenceClassification.from_pretrained(MODEL)
model.save_pretrained(MODEL)
model = torch.nn.DataParallel(model, device_ids=[0])


text = "Good night 😊"
text = preprocess(text)
encoded_input = tokenizer(text, return_tensors='pt').to(device)
print(encoded_input)
output = model(**encoded_input)
scores = output[0][0].cpu().detach().numpy()
scores = softmax(scores)
print(scores)
# # TF
# model = TFAutoModelForSequenceClassification.from_pretrained(MODEL)
# model.save_pretrained(MODEL)

# text = "Good night 😊"
# encoded_input = tokenizer(text, return_tensors='tf')
# output = model(encoded_input)
# scores = output[0][0].numpy()
# scores = softmax(scores)


def get_sentiment(text):

    encoded_input = tokenizer(text, return_tensors='pt').to(device)
    output = model(**encoded_input)
    scores = output[0][0].cpu().detach().numpy()
    scores = softmax(scores)
    return scores


{'input_ids': tensor([[    0, 12350,   363, 17841, 27969,     2]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]], device='cuda:0')}
[0.00760985 0.14581175 0.84657836]


In [ ]:
import fasttext
model = fasttext.load_model('./lid.176.bin')
def check_lang(x):
    if model.predict(x)[0][0].split('_')[-1] == 'en':
        return x
    return np.nan

In [ ]:
df =pd.read_csv('tweets_cleaned.csv',index_col=0)
df.info()


In [134]:
df2018= pd.DataFrame(df[(df.timestamp > "2017-12-31 23:59") &
                   (df.timestamp < "2019-01-01 00:00")].sort_values('timestamp'))
df2018.user.value_counts().head(25)

In [135]:
vals = pd.DataFrame(df2018.user.value_counts())
vals.reset_index(inplace=True)
vals.rename({'index': 'user', 'user': 'count'}, inplace=True, axis=1)
repeated_users = vals.head(25).user.to_list()
def check(x):
    if x in repeated_users:
        return np.nan
    else:
        return x

In [ ]:
df2018.user=df2018.user.apply(lambda x: check(x))
df2018.isna().sum()

In [ ]:
df2018['pp_text'] = df2018.text.apply(lambda x: preprocess_tweet(x))
df2018.head(20)
df2018.isna().sum()

In [ ]:
df2018.pp_text.value_counts().head(50)
df2018.text.value_counts().head(25)

In [ ]:
rep_text = [x for x in df2018.pp_text.value_counts().head(50).index]
df2018.pp_text.replace(rep_text,np.nan,inplace=True)


In [ ]:
df2018.isna().sum()
df2018.dropna(0,inplace=True)

In [ ]:
df2018.pp_text = df2018.pp_text.apply(lambda x: check_lang(x))
df2018.info()

In [ ]:
df2018.dropna(subset=['user','pp_text'],axis=0,inplace=True)
df2018.drop('text',axis=1,inplace=True)

In [ ]:
df2018.reset_index(drop=True,inplace=True)
rep_pptext = df2018.groupby(['user','pp_text']).count().sort_values('timestamp',ascending=False).head(100).reset_index().pp_text
df2018.pp_text.replace(rep_pptext.to_list(),np.nan,inplace=True)
df2018.dropna(subset=['user','pp_text'],axis=0,inplace=True)


In [ ]:
df2018.isna().sum()

In [ ]:
temp = df2018.apply(lambda row: get_sentiment(row.pp_text), axis='columns', result_type='expand')
df2018 = pd.concat([df2018, temp], axis='columns')  

In [ ]:
df2018.rename({0: 'negative', 1: 'netural',2:'positive'}, inplace=True, axis=1)
df2018

In [ ]:
bots =df2018[df2018.user.str.contains('bot')].user.value_counts().head(12)

In [ ]:
df2018.user.replace(bots.index,np.nan,inplace=True)
df2018.dropna(0,subset=['user'],inplace=True)
df2018.drop('pp_text',inplace=True,axis=1)
btc_df = pd.read_csv('./BTC-USD 2018.csv')

In [ ]:
dailiy_df = df2018.groupby(df.timestamp.dt.date).agg(
    Replies=('replies', 'sum'),Likes=('likes', 'sum'),Retweets=('retweets', 'sum'),Negative=('negative', 'mean'),Netural=('netural', 'mean'), Positive=('positive', 'mean'),)


In [ ]:
dailiy_df.reset_index(inplace=True)
dailiy_df.rename({'timestamp':'Date'},inplace=True,axis=1)
dailiy_df.columns
dailiy_df.Date = pd.to_datetime(dailiy_df.Date)
btc_df.Date = pd.to_datetime(btc_df.Date)
dailiy_df = pd.merge(dailiy_df, btc_df, on='Date')  


In [ ]:
import sweetviz
d= sweetviz.analyze(dailiy_df)
d.show_html('FinalReport.html')


In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
av_d = AV.AutoViz('dailiy_2018.csv')

In [ ]:
testdf = pd.DataFrame(dailiy_df)
testdf.drop(['Open','High','Low','Volume','Netural','Replies','Likes','Adj Close'],axis=1,inplace=True)
train = testdf[testdf.Date <'2018-11-01']
test = testdf[testdf.Date >='2018-11-01']
test

In [ ]:
from pycaret import *
s = setup(data = train, test_data = test, target = 'Close', fold_strategy = 'timeseries', numeric_features = ['Negative','Retweets','Positive'], fold = 3, transform_target = True, session_id = 123)
best = compare_models()
prediction_holdout = predict_model(best)
predictions = predict_model(best, data=testdf)
predictions

In [ ]:
import plotly.express as px

predictions['Date'] = pd.date_range(start='2018-01-01', end = '2018-12-31')
# line plot
fig = px.line(predictions, x='Date', y=["Close", "Label"], template = 'plotly_dark')
# add a vertical rectange for test-set separation
fig.show()